// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEpdOK-TPx1y3qiylWUhniuudTAG5I2Os',
    appId: '1:1053373269747:web:70a3cbcea406b77dde1986',
    messagingSenderId: '1053373269747',
    projectId: 'chat-project-a6e17',
    authDomain: 'chat-project-a6e17.firebaseapp.com',
    storageBucket: 'chat-project-a6e17.appspot.com',
    measurementId: 'G-HXNXKMZ087',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI4jJoQu57-r-QK4Kr105v3A8mmcoqbnw',
    appId: '1:1053373269747:android:8b00db433fabf268de1986',
    messagingSenderId: '1053373269747',
    projectId: 'chat-project-a6e17',
    storageBucket: 'chat-project-a6e17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKiPSt2ZHabYc3gbboIDoSaMP4yw8BMvQ',
    appId: '1:1053373269747:ios:b5f6d63f68177d43de1986',
    messagingSenderId: '1053373269747',
    projectId: 'chat-project-a6e17',
    storageBucket: 'chat-project-a6e17.appspot.com',
    iosClientId: '1053373269747-hudlt0telptp71m987dheiqiiuom6vsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKiPSt2ZHabYc3gbboIDoSaMP4yw8BMvQ',
    appId: '1:1053373269747:ios:b5f6d63f68177d43de1986',
    messagingSenderId: '1053373269747',
    projectId: 'chat-project-a6e17',
    storageBucket: 'chat-project-a6e17.appspot.com',
    iosClientId: '1053373269747-hudlt0telptp71m987dheiqiiuom6vsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
